name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./server # Cambia el directorio a "server"
      run: npm install

    - name: Run tests
      working-directory: ./server # Cambia el directorio a "server"
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }} # Uso del Secret
      run: npm test

    - name: Build
      working-directory: ./server # Cambia el directorio a "server"
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }} # Uso del Secret
      run: npm run build
